### ISSUE TITLE
Using BIAS_FF in leftFeedForward() with negative speed

### ISSUE THREAD

**Issue by Nikitarc** [ukmars/mazerunner-core#7]
motor.h  leftFeedForward()
Looks like adding a positive BIAS_FF to a negative speed is wrong.
Assuming that the speed can be negative when the robot moves backwards.

**Comment by micromouseonline** [comment]
Well spotted. Actually both feedforward calculations will be wrong since the BIAS should be multiplied by the sign of the motion.

fortunately, the value is small at about 0.12 Volts.

If you wanted to do a pull request with a correction, I will have a look at it. Otherwise it might be a little while before I get it sorted out.
